name:                hauth
version:             0.0.0.1
github:              "peri4n/knowledge"
license:             BSD3
author:              "Fabian Bull"
maintainer:          "spam+github@fbull.de"
copyright:           "2022 Fabian Bull"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/peri4n/knowledge#readme>

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- time
- pcre-heavy
- template-haskell
- aeson

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- QuasiQuotes
- TemplateHaskell

library:
  source-dirs: src

executables:
  hauth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hauth

tests:
  hauth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hauth
    - hspec
